/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as HrDashboardRouteImport } from './routes/hr/dashboard'
import { Route as HrCandidatesIndexRouteImport } from './routes/hr/candidates/index'
import { Route as CompanyAssignmentsIndexRouteImport } from './routes/company/assignments/index'
import { Route as HrCandidatesAssessmentIdRouteImport } from './routes/hr/candidates/$assessmentId'
import { Route as CompanyAssignmentsCreateRouteImport } from './routes/company/assignments/create'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HrDashboardRoute = HrDashboardRouteImport.update({
  id: '/hr/dashboard',
  path: '/hr/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HrCandidatesIndexRoute = HrCandidatesIndexRouteImport.update({
  id: '/hr/candidates/',
  path: '/hr/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAssignmentsIndexRoute = CompanyAssignmentsIndexRouteImport.update({
  id: '/company/assignments/',
  path: '/company/assignments/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrCandidatesAssessmentIdRoute =
  HrCandidatesAssessmentIdRouteImport.update({
    id: '/hr/candidates/$assessmentId',
    path: '/hr/candidates/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanyAssignmentsCreateRoute =
  CompanyAssignmentsCreateRouteImport.update({
    id: '/company/assignments/create',
    path: '/company/assignments/create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/hr/dashboard': typeof HrDashboardRoute
  '/results/$id': typeof ResultsIdRoute
  '/test': typeof TestIndexRoute
  '/company/assignments/create': typeof CompanyAssignmentsCreateRoute
  '/hr/candidates/$assessmentId': typeof HrCandidatesAssessmentIdRoute
  '/company/assignments': typeof CompanyAssignmentsIndexRoute
  '/hr/candidates': typeof HrCandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/hr/dashboard': typeof HrDashboardRoute
  '/results/$id': typeof ResultsIdRoute
  '/test': typeof TestIndexRoute
  '/company/assignments/create': typeof CompanyAssignmentsCreateRoute
  '/hr/candidates/$assessmentId': typeof HrCandidatesAssessmentIdRoute
  '/company/assignments': typeof CompanyAssignmentsIndexRoute
  '/hr/candidates': typeof HrCandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/hr/dashboard': typeof HrDashboardRoute
  '/results/$id': typeof ResultsIdRoute
  '/test/': typeof TestIndexRoute
  '/company/assignments/create': typeof CompanyAssignmentsCreateRoute
  '/hr/candidates/$assessmentId': typeof HrCandidatesAssessmentIdRoute
  '/company/assignments/': typeof CompanyAssignmentsIndexRoute
  '/hr/candidates/': typeof HrCandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/hr/dashboard'
    | '/results/$id'
    | '/test'
    | '/company/assignments/create'
    | '/hr/candidates/$assessmentId'
    | '/company/assignments'
    | '/hr/candidates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessments'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/hr/dashboard'
    | '/results/$id'
    | '/test'
    | '/company/assignments/create'
    | '/hr/candidates/$assessmentId'
    | '/company/assignments'
    | '/hr/candidates'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/hr/dashboard'
    | '/results/$id'
    | '/test/'
    | '/company/assignments/create'
    | '/hr/candidates/$assessmentId'
    | '/company/assignments/'
    | '/hr/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  HrDashboardRoute: typeof HrDashboardRoute
  ResultsIdRoute: typeof ResultsIdRoute
  TestIndexRoute: typeof TestIndexRoute
  CompanyAssignmentsCreateRoute: typeof CompanyAssignmentsCreateRoute
  HrCandidatesAssessmentIdRoute: typeof HrCandidatesAssessmentIdRoute
  CompanyAssignmentsIndexRoute: typeof CompanyAssignmentsIndexRoute
  HrCandidatesIndexRoute: typeof HrCandidatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/dashboard': {
      id: '/hr/dashboard'
      path: '/hr/dashboard'
      fullPath: '/hr/dashboard'
      preLoaderRoute: typeof HrDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/candidates/': {
      id: '/hr/candidates/'
      path: '/hr/candidates'
      fullPath: '/hr/candidates'
      preLoaderRoute: typeof HrCandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/assignments/': {
      id: '/company/assignments/'
      path: '/company/assignments'
      fullPath: '/company/assignments'
      preLoaderRoute: typeof CompanyAssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/candidates/$assessmentId': {
      id: '/hr/candidates/$assessmentId'
      path: '/hr/candidates/$assessmentId'
      fullPath: '/hr/candidates/$assessmentId'
      preLoaderRoute: typeof HrCandidatesAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/assignments/create': {
      id: '/company/assignments/create'
      path: '/company/assignments/create'
      fullPath: '/company/assignments/create'
      preLoaderRoute: typeof CompanyAssignmentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  HrDashboardRoute: HrDashboardRoute,
  ResultsIdRoute: ResultsIdRoute,
  TestIndexRoute: TestIndexRoute,
  CompanyAssignmentsCreateRoute: CompanyAssignmentsCreateRoute,
  HrCandidatesAssessmentIdRoute: HrCandidatesAssessmentIdRoute,
  CompanyAssignmentsIndexRoute: CompanyAssignmentsIndexRoute,
  HrCandidatesIndexRoute: HrCandidatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
