/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as CompanySubscriptionRouteImport } from './routes/company/subscription'
import { Route as CompanyPackagesRouteImport } from './routes/company/packages'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as CompanyAssignmentsIndexRouteImport } from './routes/company/assignments/index'
import { Route as AdminTestsIndexRouteImport } from './routes/admin/tests/index'
import { Route as AdminPackagesIndexRouteImport } from './routes/admin/packages/index'
import { Route as AdminCandidatesIndexRouteImport } from './routes/admin/candidates/index'
import { Route as GuestResultsAssessmentIdRouteImport } from './routes/guest/results.$assessmentId'
import { Route as CompanyResultsIdRouteImport } from './routes/company/results.$id'
import { Route as CompanyAssignmentsCreateRouteImport } from './routes/company/assignments/create'
import { Route as AdminTestsCreateRouteImport } from './routes/admin/tests/create'
import { Route as AdminTestsTestIdRouteImport } from './routes/admin/tests/$testId'
import { Route as AdminPackagesCreateRouteImport } from './routes/admin/packages/create'
import { Route as AdminCandidatesAssessmentIdRouteImport } from './routes/admin/candidates/$assessmentId'
import { Route as AdminPackagesPackageIdEditRouteImport } from './routes/admin/packages/$packageId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySubscriptionRoute = CompanySubscriptionRouteImport.update({
  id: '/company/subscription',
  path: '/company/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPackagesRoute = CompanyPackagesRouteImport.update({
  id: '/company/packages',
  path: '/company/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CompanyAssignmentsIndexRoute = CompanyAssignmentsIndexRouteImport.update({
  id: '/company/assignments/',
  path: '/company/assignments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestsIndexRoute = AdminTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPackagesIndexRoute = AdminPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCandidatesIndexRoute = AdminCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GuestResultsAssessmentIdRoute =
  GuestResultsAssessmentIdRouteImport.update({
    id: '/guest/results/$assessmentId',
    path: '/guest/results/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanyResultsIdRoute = CompanyResultsIdRouteImport.update({
  id: '/company/results/$id',
  path: '/company/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAssignmentsCreateRoute =
  CompanyAssignmentsCreateRouteImport.update({
    id: '/company/assignments/create',
    path: '/company/assignments/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTestsCreateRoute = AdminTestsCreateRouteImport.update({
  id: '/tests/create',
  path: '/tests/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTestsTestIdRoute = AdminTestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPackagesCreateRoute = AdminPackagesCreateRouteImport.update({
  id: '/packages/create',
  path: '/packages/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCandidatesAssessmentIdRoute =
  AdminCandidatesAssessmentIdRouteImport.update({
    id: '/candidates/$assessmentId',
    path: '/candidates/$assessmentId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminPackagesPackageIdEditRoute =
  AdminPackagesPackageIdEditRouteImport.update({
    id: '/packages/$packageId/edit',
    path: '/packages/$packageId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/assessments': typeof AssessmentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/packages': typeof CompanyPackagesRoute
  '/company/subscription': typeof CompanySubscriptionRoute
  '/results/$id': typeof ResultsIdRoute
  '/test': typeof TestIndexRoute
  '/admin/candidates/$assessmentId': typeof AdminCandidatesAssessmentIdRoute
  '/admin/packages/create': typeof AdminPackagesCreateRoute
  '/admin/tests/$testId': typeof AdminTestsTestIdRoute
  '/admin/tests/create': typeof AdminTestsCreateRoute
  '/company/assignments/create': typeof CompanyAssignmentsCreateRoute
  '/company/results/$id': typeof CompanyResultsIdRoute
  '/guest/results/$assessmentId': typeof GuestResultsAssessmentIdRoute
  '/admin/candidates': typeof AdminCandidatesIndexRoute
  '/admin/packages': typeof AdminPackagesIndexRoute
  '/admin/tests': typeof AdminTestsIndexRoute
  '/company/assignments': typeof CompanyAssignmentsIndexRoute
  '/admin/packages/$packageId/edit': typeof AdminPackagesPackageIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/assessments': typeof AssessmentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/packages': typeof CompanyPackagesRoute
  '/company/subscription': typeof CompanySubscriptionRoute
  '/results/$id': typeof ResultsIdRoute
  '/test': typeof TestIndexRoute
  '/admin/candidates/$assessmentId': typeof AdminCandidatesAssessmentIdRoute
  '/admin/packages/create': typeof AdminPackagesCreateRoute
  '/admin/tests/$testId': typeof AdminTestsTestIdRoute
  '/admin/tests/create': typeof AdminTestsCreateRoute
  '/company/assignments/create': typeof CompanyAssignmentsCreateRoute
  '/company/results/$id': typeof CompanyResultsIdRoute
  '/guest/results/$assessmentId': typeof GuestResultsAssessmentIdRoute
  '/admin/candidates': typeof AdminCandidatesIndexRoute
  '/admin/packages': typeof AdminPackagesIndexRoute
  '/admin/tests': typeof AdminTestsIndexRoute
  '/company/assignments': typeof CompanyAssignmentsIndexRoute
  '/admin/packages/$packageId/edit': typeof AdminPackagesPackageIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/assessments': typeof AssessmentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/packages': typeof CompanyPackagesRoute
  '/company/subscription': typeof CompanySubscriptionRoute
  '/results/$id': typeof ResultsIdRoute
  '/test/': typeof TestIndexRoute
  '/admin/candidates/$assessmentId': typeof AdminCandidatesAssessmentIdRoute
  '/admin/packages/create': typeof AdminPackagesCreateRoute
  '/admin/tests/$testId': typeof AdminTestsTestIdRoute
  '/admin/tests/create': typeof AdminTestsCreateRoute
  '/company/assignments/create': typeof CompanyAssignmentsCreateRoute
  '/company/results/$id': typeof CompanyResultsIdRoute
  '/guest/results/$assessmentId': typeof GuestResultsAssessmentIdRoute
  '/admin/candidates/': typeof AdminCandidatesIndexRoute
  '/admin/packages/': typeof AdminPackagesIndexRoute
  '/admin/tests/': typeof AdminTestsIndexRoute
  '/company/assignments/': typeof CompanyAssignmentsIndexRoute
  '/admin/packages/$packageId/edit': typeof AdminPackagesPackageIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assessments'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/users'
    | '/company/packages'
    | '/company/subscription'
    | '/results/$id'
    | '/test'
    | '/admin/candidates/$assessmentId'
    | '/admin/packages/create'
    | '/admin/tests/$testId'
    | '/admin/tests/create'
    | '/company/assignments/create'
    | '/company/results/$id'
    | '/guest/results/$assessmentId'
    | '/admin/candidates'
    | '/admin/packages'
    | '/admin/tests'
    | '/company/assignments'
    | '/admin/packages/$packageId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assessments'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/users'
    | '/company/packages'
    | '/company/subscription'
    | '/results/$id'
    | '/test'
    | '/admin/candidates/$assessmentId'
    | '/admin/packages/create'
    | '/admin/tests/$testId'
    | '/admin/tests/create'
    | '/company/assignments/create'
    | '/company/results/$id'
    | '/guest/results/$assessmentId'
    | '/admin/candidates'
    | '/admin/packages'
    | '/admin/tests'
    | '/company/assignments'
    | '/admin/packages/$packageId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assessments'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/users'
    | '/company/packages'
    | '/company/subscription'
    | '/results/$id'
    | '/test/'
    | '/admin/candidates/$assessmentId'
    | '/admin/packages/create'
    | '/admin/tests/$testId'
    | '/admin/tests/create'
    | '/company/assignments/create'
    | '/company/results/$id'
    | '/guest/results/$assessmentId'
    | '/admin/candidates/'
    | '/admin/packages/'
    | '/admin/tests/'
    | '/company/assignments/'
    | '/admin/packages/$packageId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AssessmentsRoute: typeof AssessmentsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CompanyPackagesRoute: typeof CompanyPackagesRoute
  CompanySubscriptionRoute: typeof CompanySubscriptionRoute
  ResultsIdRoute: typeof ResultsIdRoute
  TestIndexRoute: typeof TestIndexRoute
  CompanyAssignmentsCreateRoute: typeof CompanyAssignmentsCreateRoute
  CompanyResultsIdRoute: typeof CompanyResultsIdRoute
  GuestResultsAssessmentIdRoute: typeof GuestResultsAssessmentIdRoute
  CompanyAssignmentsIndexRoute: typeof CompanyAssignmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/subscription': {
      id: '/company/subscription'
      path: '/company/subscription'
      fullPath: '/company/subscription'
      preLoaderRoute: typeof CompanySubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/packages': {
      id: '/company/packages'
      path: '/company/packages'
      fullPath: '/company/packages'
      preLoaderRoute: typeof CompanyPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/company/assignments/': {
      id: '/company/assignments/'
      path: '/company/assignments'
      fullPath: '/company/assignments'
      preLoaderRoute: typeof CompanyAssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tests/': {
      id: '/admin/tests/'
      path: '/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AdminTestsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/packages/': {
      id: '/admin/packages/'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/candidates/': {
      id: '/admin/candidates/'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/guest/results/$assessmentId': {
      id: '/guest/results/$assessmentId'
      path: '/guest/results/$assessmentId'
      fullPath: '/guest/results/$assessmentId'
      preLoaderRoute: typeof GuestResultsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/results/$id': {
      id: '/company/results/$id'
      path: '/company/results/$id'
      fullPath: '/company/results/$id'
      preLoaderRoute: typeof CompanyResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/assignments/create': {
      id: '/company/assignments/create'
      path: '/company/assignments/create'
      fullPath: '/company/assignments/create'
      preLoaderRoute: typeof CompanyAssignmentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tests/create': {
      id: '/admin/tests/create'
      path: '/tests/create'
      fullPath: '/admin/tests/create'
      preLoaderRoute: typeof AdminTestsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tests/$testId': {
      id: '/admin/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/admin/tests/$testId'
      preLoaderRoute: typeof AdminTestsTestIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/packages/create': {
      id: '/admin/packages/create'
      path: '/packages/create'
      fullPath: '/admin/packages/create'
      preLoaderRoute: typeof AdminPackagesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/candidates/$assessmentId': {
      id: '/admin/candidates/$assessmentId'
      path: '/candidates/$assessmentId'
      fullPath: '/admin/candidates/$assessmentId'
      preLoaderRoute: typeof AdminCandidatesAssessmentIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/packages/$packageId/edit': {
      id: '/admin/packages/$packageId/edit'
      path: '/packages/$packageId/edit'
      fullPath: '/admin/packages/$packageId/edit'
      preLoaderRoute: typeof AdminPackagesPackageIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminCandidatesAssessmentIdRoute: typeof AdminCandidatesAssessmentIdRoute
  AdminPackagesCreateRoute: typeof AdminPackagesCreateRoute
  AdminTestsTestIdRoute: typeof AdminTestsTestIdRoute
  AdminTestsCreateRoute: typeof AdminTestsCreateRoute
  AdminCandidatesIndexRoute: typeof AdminCandidatesIndexRoute
  AdminPackagesIndexRoute: typeof AdminPackagesIndexRoute
  AdminTestsIndexRoute: typeof AdminTestsIndexRoute
  AdminPackagesPackageIdEditRoute: typeof AdminPackagesPackageIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminCandidatesAssessmentIdRoute: AdminCandidatesAssessmentIdRoute,
  AdminPackagesCreateRoute: AdminPackagesCreateRoute,
  AdminTestsTestIdRoute: AdminTestsTestIdRoute,
  AdminTestsCreateRoute: AdminTestsCreateRoute,
  AdminCandidatesIndexRoute: AdminCandidatesIndexRoute,
  AdminPackagesIndexRoute: AdminPackagesIndexRoute,
  AdminTestsIndexRoute: AdminTestsIndexRoute,
  AdminPackagesPackageIdEditRoute: AdminPackagesPackageIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AssessmentsRoute: AssessmentsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CompanyPackagesRoute: CompanyPackagesRoute,
  CompanySubscriptionRoute: CompanySubscriptionRoute,
  ResultsIdRoute: ResultsIdRoute,
  TestIndexRoute: TestIndexRoute,
  CompanyAssignmentsCreateRoute: CompanyAssignmentsCreateRoute,
  CompanyResultsIdRoute: CompanyResultsIdRoute,
  GuestResultsAssessmentIdRoute: GuestResultsAssessmentIdRoute,
  CompanyAssignmentsIndexRoute: CompanyAssignmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
